version: '3'
services:
  web:
    image: thecodingmachine/php:7.2-v2-cli
    ports:
      - 8080
    command: php -S 0.0.0.0:8080 -t public/
    volumes:
      - ./:/usr/src/app
    environment:
      STARTUP_COMMAND_1: composer install
      APP_ENV: local
      ENQUEUE_DSN: file://%kernel.project_dir%/var/queue
  worker:
    image: thecodingmachine/php:7.2-v2-cli
    command: ./bin/console messenger:consume -vvv
    volumes:
      - ./:/usr/src/app
    environment:
      STARTUP_COMMAND_1: composer install
      APP_ENV: local
      ENQUEUE_DSN: file://%kernel.project_dir%/var/queue
  ngrok:
    image: wernight/ngrok
    ports:
      - 4040
    environment:
      VIRTUAL_HOST: ngrok.docker
      NGROK_PORT: web:8080
